config/routes.rb
Rails.application.routes.draw do
  get 'welcome/welcome'

  get 'welcome/thank_you'
  post 'welcome/thank_you'
  get 'reports/all_data'

  root 'welcome#welcome'

end

app/models/assembly.rb
class Assembly < ActiveRecord::Base
  has_many :sequences
end

app/models/gene.rb
class Gene < ActiveRecord::Base
  belongs_to :sequence
  has_many :hits, as: :subject

  validates :sequence_id, presence: true
end

app/models/hit.rb
class Hit < ActiveRecord::Base
  belongs_to :subject, polymorphic: true

  validates :subject_id, presence: true
  validates :subject_type, presence: true
end

app/models/sequence.rb
class Sequence < ActiveRecord::Base
  belongs_to :assembly
  has_many :genes

  validates :assembly_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def all_data
    @assembly = Assembly.where(name: params[:name])
    @hits = Hit.where(subject_id: Gene.where(
      sequence_id: Sequence.where(
      assembly_id: Assembly.where(
      name: params[:name])))).order(:percent_similarity)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome
  end

  def thank_you
    @email = params[:email]
    @name = params[:name]
#   EmailBlasterJob.perform_later(params[:name])
    HitsMailer.report(@email, @name).deliver_now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DatabaseOptimizations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/all_data.html.erb
<h1>Hits for <%= @assembly.name %></h1>
<p>Number of hits: <%= @hits.length %></p>
<table>
  <thead>
    <tr>
      <th>Matching Gene Name</th>
      <th>Matching DNA</th>
      <th>Percent Similarity</th>
    </tr>
  </thead>
  <tbody>
    <% @hits.each do |h| %>
      <tr>
        <td><%= h.match_gene_name %></td>
        <td><%= h.match_gene_dna.first(100) %></td>
        <td><%= h.percent_similarity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/thank_you.html.erb
<h4>Thank you for your time. An email will be sent to <%= @email %> upon completion</h4>

app/views/welcome/welcome.html.erb
<h1>Welcome to the Gene Machine</h1>
<p>Data from this database takes a while to generate, if you would like,
  you can enter an email address and the name of the data you want to access and
  the data will be sent to you after it is generated.
</p>

<h4>There are 100 available names to chose from, starting at a1 and going to a100</h4>

<%= form_tag welcome_thank_you_path do %>
  <%= text_field_tag "email", nil, placeholder: "Email" %>
  <%= text_field_tag "name", nil, placeholder: "Assembly Name" %>

  <%= submit_tag %>
<% end %>